apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    dev.azure.com/project-repo: 'Packer - Tests et documentation/Packer - Tests et documentation'
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
